# Generated by Django 2.1.3 on 2019-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCurrencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=6)),
                ('rate', models.CharField(max_length=10)),
                ('change', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PopularCurrencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=10)),
                ('change', models.CharField(max_length=6)),
            ],
        ),
    ]
