# Generated by Django 2.1.3 on 2019-01-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcurrencymodel',
            name='change',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='allcurrencymodel',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='popularcurrencymodel',
            name='change',
            field=models.CharField(max_length=10),
        ),
    ]
